#!/bin/zsh

setopt -e

[ -f .config ] && rm .config
make ARCH=arm bcmrpi_defconfig
make ARCH=arm CROSS_COMPILE=/usr/bin/armv6j-hardfloat-linux-gnueabi- oldconfig

loc=$(git log --date=short -n 1000 | grep "^Date" | sort | tail -n 1 \
	| awk '$1 == "Date:" { print $2 }' | tr -d - | head -n 1)
sed -e "/^CONFIG_LOCALVERSION/s:=.*:=\"-$loc\":" -i .config

make ARCH=arm CROSS_COMPILE=/usr/bin/armv6j-hardfloat-linux-gnueabi- -j2

TMPDIR=$(mktemp -d "${TMP-/tmp}/${0##*/}"-XXXXX)
trap "[ -d \"${TMPDIR}\" ] && rm -r \"${TMPDIR}\"" SIGINT ZERR
mkdir "${TMPDIR}"/boot

make ARCH=arm CROSS_COMPILE=/usr/bin/armv6j-hardfloat-linux-gnueabi- modules_install INSTALL_MOD_PATH="${TMPDIR}"
make ARCH=arm CROSS_COMPILE=/usr/bin/armv6j-hardfloat-linux-gnueabi- install INSTALL_PATH="${TMPDIR}"/boot
vmlinuz=$(ls -1 "${TMPDIR}"/boot/vmlinu*)
kernelimg=${vmlinuz/vmlinuz-/kernel.img-}
#imagetool-uncompressed.py "${vmlinuz}" "${kernelimg}"
#rm -v "${vmlinuz}"
mv -v "${vmlinuz}" "${kernelimg}"
rm -v "${TMPDIR}"/lib/modules/*/build
rm -v "${TMPDIR}"/lib/modules/*/source

PV=$(basename $(ls -d ${TMPDIR}/lib/modules/*))
PV=${PV/-raspberrypi-/_pre-r}
PV=${PV%%+}
A=$(portageq distdir)/raspberrypi-image-${PV}.tar.xz
tar cvJf "${A}" -C "${TMPDIR}" .

echo "rsync -avP --bwlimit=80 --no-owner --no-group \"${A}\" dev.gentoo.org:public_html/raspberrypi-image/"

